concurrent = 6
check_interval = 0

[[runners]]
  name = "bj frontend shell gitlab runner"
  url = "http://xxx/"
  token = "xxx"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "jsongo/gitlab-runner:ansible"
    privileged = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock:ro", "/cache", "/home/push/.ssh:/root/.ssh", "/etc/docker/daemon.json:/etc/docker/daemon.json"]
    shm_size = 0
  [runners.cache]