#!/bin/bash

# gitlab-ci-multi-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}
# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

# 退出的时候取消注册
# unregister() {
#     echo "Unregistering runner ${RUNNER_NAME} ..."
#     gitlab-runner unregister -t "$(gitlab-runner list 2>&1 | tail -n1 | awk '{print $4}' | cut -d'=' -f2)" -n ${RUNNER_NAME}
#     exit $?
# }
# trap 'unregister' EXIT HUP INT QUIT PIPE TERM

# launch gitlab-ci-multi-runner passing all arguments
if [ ! -f /etc/gitlab-runner/config.toml ] || [ $TO_REGISTER ]; then
    gitlab-runner register --docker-privileged
fi
echo "Start to run..."
exec gitlab-ci-multi-runner $@
